### ISSUE TITLE
example doesnt work

### ISSUE THREAD

**Issue by mason-rogers** [foxbot/gavalink#5]
the example you provided in the examples/ folder doesn't work, after correcting the port to the default one on lavalink to 2333 for both ws and http. It gives me an error related to strconv.
` strconv.Atoi: parsing "": invalid syntax`

This is caused by node.go when it tried to get the version from the `Lavalink-Major-Version` header, any clue when this can be fixed because I kinda ned it for a project rn...

**Comment by tyhi** [comment]
#4 will fix this when merged. You could also use his fork until then if you need it right away. https://github.com/zekroTJA/gavalink

**Comment by mason-rogers** [comment]
any idea when it will be merged

**Comment by tyhi** [comment]
I wouldn't know. @foxbot
